#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python manage.py migrate

python manage.py collectstatic --noinput

# Seed the db
if [[ $* == *--seed-e2e ]]
then
   python manage.py loaddata db.json
fi

# Seed the db if not already seeded
if [[ $* == *--single-seed-e2e ]]
then
   if [[ $(python manage.py number_of_users) != 1 ]] # This is one because django seems to auto seed an anonymous user
   then
      echo "Skipping seeding as users in db"
   else
      echo "Seeding DB"
      python manage.py loaddata db.json
   fi
fi

python manage.py runserver 0.0.0.0:8000
