# Generated by Django 3.2.5 on 2021-07-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productions", "0001_initial"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcessionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("percentage", models.FloatField()),
                (
                    "performances",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discounts",
                        to="productions.Performance",
                    ),
                ),
                (
                    "seat_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venues.seatgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscountRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.SmallIntegerField()),
                (
                    "concession_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discounts.concessiontype",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="discounts.discount",
                    ),
                ),
            ],
        ),
    ]
