# Generated by Django 3.2.8 on 2021-11-13 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountrequirement",
            name="concession_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_requirements",
                to="discounts.concessiontype",
            ),
        ),
    ]
