# Generated by Django 3.2.8 on 2021-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0002_alter_discountrequirement_concession_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
