# Generated by Django 3.2.8 on 2021-11-24 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0003_alter_discount_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="percentage",
            field=models.FloatField(
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ]
            ),
        ),
    ]
