# Generated by Django 3.2.10 on 2022-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0004_alter_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountrequirement",
            name="number",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
