# Generated by Django 3.2.16 on 2023-01-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0005_alter_discountrequirement_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="concessiontype",
            name="max_per_booking",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
