repos:
- hooks:
  - id: trailing-whitespace
  - exclude: .txt$
    id: end-of-file-fixer
  - id: check-yaml
  - exclude: ^.devcontainer/
    id: check-json
  - args:
    - --remove
    id: fix-encoding-pragma
  - id: forbid-new-submodules
  - args:
    - --fix=lf
    description: Forces to replace line ending by the UNIX 'lf' character.
    id: mixed-line-ending
  - args:
    - --maxkb=500
    id: check-added-large-files
  - args:
    - --branch
    - main
    id: no-commit-to-branch
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
- hooks:
  - exclude: ^t2\.py$
    id: isort
  repo: https://github.com/PyCQA/isort
  rev: 5.8.0
- hooks:
  - id: black
    language_version: python3.10
  repo: https://github.com/psf/black
  rev: 22.3.0
- hooks:
  - args:
    - --in-place
    - --remove-all-unused-imports
    - --remove-unused-variable
    id: autoflake
  repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.1
- hooks:
  - exclude: migrations/
    id: pylint
  repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a3
- hooks:
  - additional_dependencies:
    - django-autoslug==1.9.8
    - shortuuid>=1.0.1
    - django-filter==21.1
    - Pillow>=8.1.2
    - django-cors-headers==3.11.0
    - django-admin-confirm==0.2.4
    - django-configurations==2.3.2
    - django-environ==0.8.1
    - xlsxwriter==3.0.3
    - html2text==2020.1.16
    - django==3.2.12
    - django-guardian==2.4.0
    - django_tiptap==0.0.10
    - djangorestframework==3.13.1
    - django-nonrelated-inlines==0.1.1
    - graphene==2.1.9
    - graphene-django==2.15.0
    - django-graphql-auth==0.3.16
    - django-graphql-jwt==0.3.0
    - PyJWT==1.7.0
    - squareup>=9.0.0.20210226
    - sentry-sdk==1.5.6
    - whitenoise==6.0.0
    - django-anymail[amazon_ses]==8.5
    - django-inlinecss==0.3.0
    - timezonefinder==5.2.0
    - pytz==2021.3
    - django-celery-results==2.2.0
    - redis==4.1.4
    - pre-commit >= 2.11.0
    - black >= 21.10b0
    - isort >= 5.10.1
    - pylint >= 2.13.0
    - django-stubs >= 1.10.1
    - types-python-dateutil==2.8.10
    - pytest >= 6.2.2
    - pytest-sugar >= 0.9.4
    - pytest-cov >= 2.11.1
    - pytest-django >= 0.2.0
    - pytest-factoryboy >= 2.1.0
    - coveralls >= 3.0.1
    - factory-boy==3.2.1
    - faker==13.3.3; python_version >= '3.6'
    - jedi==0.18.1; python_version >= '3.6'
    - psycopg2-binary
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.930
