repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: fix-encoding-pragma
      args: ['--remove']
    - id: forbid-new-submodules
    - id: mixed-line-ending
      args: ['--fix=lf']
      description: Forces to replace line ending by the UNIX 'lf' character.
    # - id: pretty-format-json
    #  args: ['--no-sort-keys']
    - id: check-added-large-files
      args: ['--maxkb=500']
    - id: no-commit-to-branch
      args: [--branch, main]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        exclude: ^t2\.py$


  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
    - id: black
      language_version: python3.9

  # Flake8 checks what errors there are and gives code
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.8.4
  #   hooks:
  #   - id: flake8

  # Autoflake will fix the above errors
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v3.0.0a3'  # Use the sha / tag you want to point at
    hooks:
      - id: pylint
        exclude: migrations/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        additional_dependencies: [django-stubs,dj-database-url,django-filter,django-cors-headers,django-autoslug,graphene-django,psycopg2-binary,django-graphql-auth,gunicorn,shortuuid,squareup,django-environ]
