repos:
- hooks:
  - id: trailing-whitespace
  - exclude: .txt$
    id: end-of-file-fixer
  - id: check-yaml
  - exclude: ^.devcontainer/
    id: check-json
  - args:
    - --remove
    id: fix-encoding-pragma
  - id: forbid-new-submodules
  - args:
    - --fix=lf
    description: Forces to replace line ending by the UNIX 'lf' character.
    id: mixed-line-ending
  - args:
    - --maxkb=500
    id: check-added-large-files
  - args:
    - --branch
    - main
    id: no-commit-to-branch
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
- hooks:
  - exclude: ^t2\.py$
    id: isort
  repo: https://github.com/PyCQA/isort
  rev: 5.12.0
- hooks:
  - id: black
    language_version: python3.12
  repo: https://github.com/psf/black
  rev: 22.3.0
- hooks:
  - args:
    - --in-place
    - --remove-all-unused-imports
    - --remove-unused-variable
    id: autoflake
  repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.1
- hooks:
  - exclude: migrations/
    id: pylint
  repo: https://github.com/pycqa/pylint
  rev: v2.15.0
- hooks:
  - additional_dependencies:
    - django-autoslug==1.9.9
    - shortuuid==1.0.13
    - django-filter==25.2
    - Pillow==12.1.1
    - django-cors-headers==4.9.0
    - django-admin-confirm==1.0.1
    - django-configurations==2.5.1
    - django-environ==0.12.0
    - xlsxwriter==3.2.9
    - html2text==2025.4.15
    - django==6.0.3
    - django-guardian==3.2.0
    - django_tiptap==0.0.18
    - djangorestframework==3.16.1
    - django-nonrelated-inlines==0.2
    - graphene==3.4.3
    - graphene-django==3.2.3
    - graphql-core==3.2.6
    - django-graphql-jwt==0.4.0
    - PyJWT==2.12.0
    - pydantic==2.12.3
    - squareup==44.0.1.20260122
    - sentry-sdk==2.42.0
    - whitenoise==6.11.0
    - django-anymail[amazon_ses]==13.1
    - django-inlinecss-redux==0.4.0
    - timezonefinder==8.1.0
    - pytz==2025.2
    - types-pytz==2025.2.0.20250809
    - django-celery-results==2.6.0
    - redis==6.4.0
    - pre-commit >= 2.11.0
    - black >= 22.3.0
    - isort >= 5.10.1
    - pylint >= 2.14.0
    - django-stubs==1.13.0
    - types-python-dateutil==2.8.19.10
    - pytest >= 6.2.2
    - pytest-sugar >= 0.9.4
    - pytest-cov >= 2.11.1
    - pytest-django >= 0.2.0
    - pytest-factoryboy >= 2.1.0
    - coveralls >= 3.0.1
    - factory-boy==3.2.1
    - faker==17.6.0; python_version >= '3.6'
    - jedi==0.18.2; python_version >= '3.6'
    - psycopg2==2.9.11
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.981
