version: '3'

volumes:
  uobtheatre_local_postgres_data: {}
  uobtheatre_local_postgres_data_backups: {}

services:
  api:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: uobtheatre_api_local_django
    container_name: uobtheatre-api
    depends_on:
      - postgres
    volumes:
      - .:/app/uobtheatre-api:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start --single-seed-e2e

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: uobtheatre_api_production_postgres
    container_name: uobtheatre-postgres
    volumes:
      - uobtheatre_local_postgres_data:/var/lib/postgresql/data:Z
      - uobtheatre_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  adminer:
    image: adminer
    ports:
      - 8001:8080
