site_name: uobtheatre-api
site_description: API for uobtheatre
repo_url: https://github.com/BristolSTA/uobtheatre-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/BristolSTA">BristolSTA</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
