# Generated by Django 3.2.18 on 2024-07-21 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The message displayed in the body of the banner.')),
                ('active', models.BooleanField(default=True, help_text='Whether the message is active. Inactive messages will not be displayed, even if display_start is in the past.')),
                ('indefinite_override', models.BooleanField(default=False, help_text='If True, the message will be displayed without a Date/Time/Duration if it is ongoing, and without a duration if it is in the future. In addition, it will continue to display even after the event_end until either active or indefinite_override is set to False.')),
                ('display_start', models.DateTimeField(help_text='When the message should start being displayed on the website. If null, the message will be displayed immediately.', null=True)),
                ('event_start', models.DateTimeField(help_text='When the banner shows the event will begin (date and time).')),
                ('event_end', models.DateTimeField(help_text='When the event will end. Used both to calculate duration and to know when to stop displaying the message.')),
                ('type', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('INFORMATION', 'Information'), ('ALERT', 'Alert')], default='MAINTENANCE', help_text='The type of message, which informs how it is displayed. Maintenance messages are displayed in yellow if upcoming, red if ongoing. Information messages are displayed in yellow information text. Alert messages are displayed in red text.', max_length=11)),
                ('dismissal_policy', models.CharField(choices=[('DEFAULT', 'Dismissable (Default)'), ('SINGLE', 'Single-Session Only'), ('BANNED', 'Prevented')], default='DEFAULT', help_text="The policy for a message's dismissal. By default messages are dismissable, and this choice is stored in the cache until the event is over. Single-Session Only messages can be dismissed, but dismissal is not cached. Prevented messages cannot be dismissed by the user.", max_length=7)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_site_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Message',
                'verbose_name_plural': 'Site Messages',
            },
        ),
    ]
