# Generated by Django 3.2.25 on 2025-09-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_messages', '0002_alter_message_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='display_location',
            field=models.CharField(choices=[('BANNER', 'Banner'), ('LANDING_MODAL', 'Landing Modal'), ('BOOKING_MODAL', 'Booking Modal'), ('PRODUCTION_CREATION_MODAL', 'Production Creation/Edit Modal')], default='BANNER', help_text='The location on the site where the message should be displayed. Banner messages are displayed in a banner at the top of the page. Landing Modal messages are displayed in a modal on the landing page. Booking Modal messages are displayed in a modal on the booking page. Production Creation/Edit Modal messages are displayed in a modal on the production creation and editing page.', max_length=25),
        ),
    ]
