# Generated by Django 3.2.25 on 2025-09-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_messages", "0003_message_display_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="title",
            field=models.CharField(
                default="Site Message",
                help_text="A title for the message. Displayed prominently in modals, but not in banners.",
                max_length=255,
            ),
        ),
    ]
