# Generated by Django 3.2.25 on 2025-10-06 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_messages", "0005_auto_20251006_1022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="display_start",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the message should start being displayed on the website. Used to schedule messages in advance, and to determine whether the message should be displayed.",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="event_end",
            field=models.DateTimeField(
                help_text="When the event will end. Used both to calculate duration, which is displayed when in banner display location, and to determine whether the message should be displayed."
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="event_start",
            field=models.DateTimeField(
                help_text="When the event will start. Used both to calculate duration, and displayed when in banner display location."
            ),
        ),
    ]
