# Generated by Django 4.2.25 on 2025-10-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_messages", "0006_auto_20251006_1612"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="creator",
            new_name="user",
        ),
    ]
