# Generated by Django 3.1.3 on 2020-11-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("societies", "__first__"),
        ("productions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="society",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="societies.society",
            ),
        ),
        migrations.DeleteModel(
            name="Society",
        ),
    ]
