# Generated by Django 3.1.3 on 2020-11-10 20:04

from django.db import migrations, models
import django.db.models.deletion
import uobtheatre.productions.models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, uobtheatre.productions.models.TimeStampedModel),
        ),
        migrations.AddField(
            model_name="production",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="description",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="featured_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="production",
            name="poster_image",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="production",
            name="subtitle",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="society",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="production",
            name="society",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="productions.society",
            ),
        ),
    ]
