# Generated by Django 3.1.3 on 2020-11-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
