# Generated by Django 3.2.6 on 2021-08-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0002_auto_20210805_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("CLOSED", "Closed"),
                    ("COMPLETE", "Complete"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
