# Generated by Django 3.1.3 on 2020-11-10 21:02

from django.db import migrations, models
import django.db.models.deletion
import uobtheatre.productions.models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0002_auto_20201110_2004"),
    ]

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateTimeField()),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productions.production",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productions.venue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, uobtheatre.productions.models.TimeStampedModel),
        ),
    ]
