# Generated by Django 3.2.6 on 2021-08-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0003_production_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="production",
            options={
                "ordering": ["id"],
                "permissions": (("boxoffice", "Can use boxoffice for this show"),),
            },
        ),
    ]
