# Generated by Django 3.2.7 on 2021-10-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0005_alter_production_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="production",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("boxoffice", "Can use boxoffice for this production"),
                    ("sales", "Can view sales for this production"),
                ),
            },
        ),
    ]
