# Generated by Django 3.2.8 on 2021-10-08 17:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productions", "0006_alter_production_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=True, populate_from="name", unique=True
            ),
        ),
    ]
