# Generated by Django 3.2.9 on 2021-12-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0007_alter_production_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="production",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("boxoffice", "Can use boxoffice for this production"),
                    (
                        "view_bookings",
                        "Can inspect bookings and users for this production",
                    ),
                    ("sales", "Can view sales for this production"),
                ),
            },
        )
    ]
