# Generated by Django 3.2.8 on 2021-11-11 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productions", "0007_alter_production_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="production",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("boxoffice", "Can use boxoffice for this production"),
                    ("sales", "Can view sales for this production"),
                    ("force_change_production", "Can edit production once live"),
                    (
                        "approve_production",
                        "Can approve production pending publication",
                    ),
                ),
            },
        ),
    ]
