# Generated by Django 3.2.8 on 2021-11-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("societies", "0006_alter_society_options"),
        ("productions", "0008_alter_production_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="production",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("boxoffice", "Can use boxoffice for this production"),
                    ("sales", "Can view sales for this production"),
                    ("force_change_production", "Can edit production once live"),
                    (
                        "approve_production",
                        "Can approve production pending publication",
                    ),
                ),
            },
        ),
        migrations.AlterField(
            model_name="production",
            name="society",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="productions",
                to="societies.society",
            ),
            preserve_default=False,
        ),
    ]
