# Generated by Django 3.2.8 on 2021-11-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0009_auto_20211113_1930"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="production",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("boxoffice", "Can use boxoffice for this production"),
                    ("sales", "Can view sales for this production"),
                    ("force_change_production", "Can edit production once this live"),
                    (
                        "approve_production",
                        "Can approve production pending publication",
                    ),
                ),
            },
        ),
        migrations.AlterField(
            model_name="production",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending approval"),
                    ("Approved", "Approved (not published)"),
                    ("PUBLISHED", "Published (Can view on the site)"),
                    ("CLOSED", "Closed (Ready for money transfers)"),
                    ("COMPLETE", "Complete (Show finished and all money settled)"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
