# Generated by Django 3.2.9 on 2021-11-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0011_alter_production_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending approval"),
                    ("APPROVED", "Approved"),
                    ("PUBLISHED", "Published"),
                    ("CLOSED", "Closed"),
                    ("COMPLETE", "Complete"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
