# Generated by Django 3.2.9 on 2021-12-11 13:49

from django.db import migrations, models

import uobtheatre.utils.form_validators


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0012_alter_production_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="facebook_event",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    uobtheatre.utils.form_validators.OptionalSchemeURLValidator()
                ],
            ),
        ),
    ]
