# Generated by Django 3.2.9 on 2022-01-01 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productions", "0008_auto_20211202_1601"),
        ("productions", "0013_alter_production_facebook_event"),
    ]

    operations = []
