# Generated by Django 3.2.9 on 2022-01-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("societies", "0006_alter_society_options"),
        ("productions", "0014_merge_20220101_1347"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="production",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("boxoffice", "Can use boxoffice for production"),
                    ("sales", "Can view sales for production"),
                    ("force_change_production", "Can edit production once live"),
                    (
                        "view_bookings",
                        "Can inspect bookings and users for this production",
                    ),
                    (
                        "approve_production",
                        "Can approve production pending publication",
                    ),
                ),
            },
        ),
        migrations.AlterField(
            model_name="production",
            name="facebook_event",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="production",
            name="society",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productions",
                to="societies.society",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("PUBLISHED", "Published"),
                    ("CLOSED", "Closed"),
                    ("COMPLETE", "Complete"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
