# Generated by Django 3.2.9 on 2022-01-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0009_alter_production_status"),
        ("productions", "0015_auto_20220101_1348"),
    ]

    operations = []
