# Generated by Django 3.2.10 on 2022-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productions", "0015_auto_20220101_1348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performanceseatgroup",
            name="capacity",
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="performanceseatgroup",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
