# Generated by Django 3.2.9 on 2022-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0016_merge_20220102_0940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("PUBLISHED", "Published"),
                    ("CLOSED", "Closed"),
                    ("COMPLETE", "Complete"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
