# Generated by Django 3.2.10 on 2022-01-13 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productions", "0016_auto_20220113_1416"),
        ("productions", "0017_alter_production_status"),
    ]

    operations = []
