# Generated by Django 3.2.13 on 2022-05-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0019_production_venues"),
    ]

    operations = [
        migrations.AddField(
            model_name="performance",
            name="interval_duration_mins",
            field=models.IntegerField(null=True),
        ),
    ]
