# Generated by Django 3.2.12 on 2022-04-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0019_production_venues'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='box_office_clearance_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='stage_clearance_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
