# Generated by Django 3.2.13 on 2022-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0020_performance_interval_length_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="interval_duration_mins",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
