# Generated by Django 3.2.13 on 2022-06-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0021_auto_20220612_1317"),
    ]

    operations = [
        migrations.CreateModel(  # TODO: Won't preserve exisiting relations!
            name="ProductionContentWarning",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("information", models.TextField(null=True)),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productions.production",
                    ),
                ),
                (
                    "warning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productions.contentwarning",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="production",
            name="warnings",
            field=models.ManyToManyField(
                blank=True,
                through="productions.ProductionContentWarning",
                to="productions.ContentWarning",
            ),
        ),
        migrations.RenameField(
            model_name="production",
            old_name="warnings",
            new_name="content_warnings",
        ),
    ]
