# Generated by Django 3.2.13 on 2022-08-08 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productions", "0021_alter_performance_interval_duration_mins"),
        ("productions", "0023_auto_20220707_1722"),
    ]

    operations = []
