# Generated by Django 3.2.15 on 2022-09-01 18:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0024_merge_20220808_2050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="interval_duration_mins",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productioncontentwarning",
            name="production",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warnings_pivot",
                to="productions.production",
            ),
        ),
    ]
