# Generated by Django 3.2.16 on 2022-12-10 20:56

import django_tiptap.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0025_auto_20220904_1804"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contentwarning",
            name="long_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="production",
            name="description",
            field=django_tiptap.fields.TipTapTextField(blank=True, null=True),
        ),
    ]
