# Generated by Django 3.2.15 on 2022-09-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0025_auto_20220903_1719"),
    ]

    operations = [
        migrations.RenameField(
            model_name="production",
            old_name="support_email",
            new_name="contact_email",
        ),
    ]
