# Generated by Django 3.2.13 on 2022-09-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0025_auto_20220903_1859"),
    ]

    operations = [
        migrations.RenameField(
            model_name="production",
            old_name="excerpt_text",
            new_name="short_description",
        ),
    ]
