# Generated by Django 3.2.14 on 2022-09-23 11:59

import django_tiptap.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0025_auto_20220904_1804"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentwarning",
            name="long_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="production",
            name="description",
            field=django_tiptap.fields.TipTapTextField(blank=True, null=True),
        ),
    ]
