# Generated by Django 3.2.18 on 2023-09-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0026_auto_20221210_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['id'], 'permissions': (('boxoffice', 'Can use boxoffice for production'), ('sales', 'Can view sales for production'), ('force_change_production', 'Can edit production once live'), ('view_bookings', 'Can inspect bookings and users for this production'), ('approve_production', 'Can approve production pending publication'), ('transfer_booking', 'Can transfer a booking to another performance'))},
        ),
    ]
