# Generated by Django 3.2.25 on 2025-03-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0027_production_production_alert"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="production",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("boxoffice", "Can use box office for production"),
                    ("sales", "Can view sales for production"),
                    ("force_change_production", "Can change production once live"),
                    (
                        "view_bookings",
                        "Can inspect bookings and users for this production",
                    ),
                    ("approve_production", "Can approve production"),
                    ("comp_tickets", "Can issue complimentary tickets"),
                ),
            },
        ),
    ]
