# Generated by Django 3.2.25 on 2024-10-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0027_production_production_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="performance",
            name="is_relaxed",
            field=models.BooleanField(default=False),
        ),
    ]
