# Generated by Django 3.2.25 on 2025-02-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0028_performance_is_relaxed"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelaxedCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_description", models.CharField(max_length=255)),
                ("long_description", models.TextField(blank=True, null=True)),
                ("help_text", models.TextField(blank=True, null=True)),
                ("default_relaxed", models.BooleanField(default=False)),
                ("default_sensory_friendly", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="performance",
            name="relaxed_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="performance",
            name="relaxed_categories",
            field=models.ManyToManyField(blank=True, to="productions.RelaxedCategory"),
        ),
    ]
