# Generated by Django 3.2.25 on 2025-05-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0028_alter_production_options'),
        ('productions', '0029_auto_20250228_2247'),
    ]

    operations = [
    ]
