# Generated by Django 3.2.25 on 2025-10-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0029_alter_production_options"),
        ("productions", "0030_merge_20250506_1601"),
    ]

    operations = []
