# Generated by Django 3.2.25 on 2025-10-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0031_merge_20251022_2210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="is_relaxed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this performance will be displayed as being relaxed/adapted in some way, enables the 'Relaxed', 'Sensory Friendly' etc. labels on performance tiles.",
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="relaxed_name",
            field=models.CharField(
                blank=True,
                help_text="The type of performance that this will be if the 'is relaxed' field is true, e.g. 'Relaxed' or 'Sensory Friendly'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="relaxedcategory",
            name="default_relaxed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this category is part of the 'Relaxed Performance' default selections.",
            ),
        ),
        migrations.AlterField(
            model_name="relaxedcategory",
            name="default_sensory_friendly",
            field=models.BooleanField(
                default=False,
                help_text="Whether this category is part of the 'Sensory Friendly Performance' default selections.",
            ),
        ),
        migrations.AlterField(
            model_name="relaxedcategory",
            name="help_text",
            field=models.TextField(
                blank=True,
                help_text="Any additional information that helps the production team to decide whether to select this category – only shown on the admin panel.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="relaxedcategory",
            name="long_description",
            field=models.TextField(
                blank=True,
                help_text="Long description of the category only shown one the user expands the category in the categories list.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="relaxedcategory",
            name="short_description",
            field=models.CharField(
                help_text="Short description of the category, displayed in the categories display as the 'title' of each category.",
                max_length=255,
            ),
        ),
    ]
