# Generated by Django 3.2.25 on 2025-12-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("societies", "0007_society_su_status"),
        ("productions", "0032_auto_20251025_1911"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="supporting_societies",
            field=models.ManyToManyField(
                related_name="supporting_productions", to="societies.Society"
            ),
        ),
    ]
