# Generated by Django 3.2.6 on 2021-08-19 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("societies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="society",
            name="members",
            field=models.ManyToManyField(
                related_name="societies", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
