# Generated by Django 3.2.7 on 2021-09-24 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("societies", "0003_alter_society_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="society",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="societies", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
