# Generated by Django 3.2.7 on 2021-09-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("societies", "0004_alter_society_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="society",
            name="contact",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="society",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
