# Generated by Django 3.2.25 on 2024-10-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("societies", "0006_alter_society_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="society",
            name="su_status",
            field=models.BooleanField(default=True),
        ),
    ]
