# Generated by Django 3.2.12 on 2022-03-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0006_alter_society_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='square_pos_location',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='square_pos_sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
