# Generated by Django 3.2.6 on 2021-08-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="building_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="building_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
