# Generated by Django 3.2.25 on 2025-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_auto_20210805_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="what3words",
            field=models.CharField(
                blank=True,
                help_text="A what3words address, taking the form 'word.word.word'",
                max_length=255,
                null=True,
            ),
        ),
    ]
