# Generated by Django 3.1.5 on 2021-01-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("productions", "0001_initial"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="performances",
            field=models.ManyToManyField(
                blank=True, related_name="discounts", to="productions.Performance"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="seat_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="venues.seatgroup",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="performance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="bookings",
                to="productions.performance",
            ),
        ),
    ]
