# Generated by Django 3.2.7 on 2021-09-23 10:43

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 9, 23, 10, 58, 57, 145346, tzinfo=utc)
            ),
        ),
    ]
