# Generated by Django 3.1.4 on 2020-12-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consessiontype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
