# Generated by Django 3.2.7 on 2021-09-23 22:23

from django.db import migrations, models

import uobtheatre.bookings.models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="one_in_progress_booking_per_user_per_performance",
        ),
        migrations.AddField(
            model_name="booking",
            name="expires_at",
            field=models.DateTimeField(
                default=uobtheatre.bookings.models.generate_expires_at
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("status", "performance", "user_id"),
                name="one_in_progress_booking_per_user_per_performance",
            ),
        ),
    ]
