# Generated by Django 3.1.4 on 2020-12-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='percentagemisccost',
            old_name='percentage',
            new_name='value',
        ),
    ]
