# Generated by Django 3.2.9 on 2021-11-28 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_auto_20210923_2223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="admin_discount_percentage",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="misccost",
            name="percentage",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
