# Generated by Django 3.2.7 on 2021-09-23 11:34

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_expires_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="one_in_progress_booking_per_user_per_performance",
        ),
        migrations.AlterField(
            model_name="booking",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 9, 23, 11, 49, 49, 195383, tzinfo=utc)
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("status", "performance", "user_id"),
                name="one_in_progress_booking_per_user_per_performance",
            ),
        ),
    ]
