# Generated by Django 3.2.9 on 2021-12-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_auto_20210923_2223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("CANCELLED", "Cancelled"),
                    ("PAID", "Paid"),
                    ("LOCKED", "Locked"),
                    ("REFUNDED", "Refunded"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
