# Generated by Django 3.1.4 on 2021-01-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20201231_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='percentagemisccost',
            old_name='value',
            new_name='percentage',
        ),
    ]
