# Generated by Django 3.2.10 on 2022-01-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_auto_20211128_2108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("CANCELLED", "Cancelled"),
                    ("PAID", "Paid"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
