# Generated by Django 3.2.9 on 2022-01-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_alter_booking_status"),
        ("bookings", "0004_auto_20211128_2108"),
    ]

    operations = []
