# Generated by Django 3.2.12 on 2022-10-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accessibility_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
