# Generated by Django 3.2.11 on 2022-05-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transfered_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transfered_from', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='misccost',
            name='type',
            field=models.CharField(choices=[('Booking', 'Applied to booking purchase'), ('BookingTransfer', 'Applied to a booking transfer')], default='Booking', max_length=24),
            preserve_default=False,
        ),
    ]
