# Generated by Django 3.2.13 on 2022-05-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="assessibility_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
