# Generated by Django 3.2.15 on 2022-10-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0006_alter_ticket_checkin_to_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="accessibility_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
