# Generated by Django 3.2.12 on 2022-05-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20220511_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='transfered_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='_transfered_from', to='bookings.booking'),
        ),
    ]
