# Generated by Django 3.2.18 on 2023-09-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_accessibility_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transferred_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bookings.booking'),
        ),
    ]
