# Generated by Django 3.2.25 on 2025-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_booking_accessibility_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("CANCELLED", "Cancelled"),
                    ("PAID", "Paid"),
                    ("REFUND_PROCESSING", "Refund Processing"),
                    ("REFUNDED", "Refunded"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
