# Generated by Django 3.2.25 on 2025-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="accessibility_info_updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="previous_accessibility_info",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
