# Generated by Django 4.2.25 on 2025-10-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_auto_20250513_2106"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="checked_in_by",
            new_name="checked_in_user",
        ),
    ]
