# Generated by Django 3.2.25 on 2025-05-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_auto_20250513_2106"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"permissions": (("refund_booking", "Can refund booking"),)},
        ),
    ]
