# Generated by Django 3.2.25 on 2025-05-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0012_auto_20250516_1307"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="refund_support_ticket",
            field=models.TextField(blank=True, null=True),
        ),
    ]
