# Generated by Django 3.2.6 on 2021-08-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CARD", "Card"),
                    ("SQUARE_ONLINE", "Square online"),
                    ("SQUARE_POS", "Square point of sale"),
                ],
                default="SQUARE_ONLINE",
                max_length=20,
            ),
        ),
    ]
