# Generated by Django 3.2.7 on 2021-09-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_alter_payment_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="app_fee",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_fee",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
