# Generated by Django 3.2.9 on 2022-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_auto_20211231_1219"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("CASH", "CASH"),
                    ("CARD", "CARD"),
                    ("SQUARE_POS", "SQUARE_POS"),
                    ("SQUARE_ONLINE", "SQUARE_ONLINE"),
                    ("MANUAL_REFUND", "MANUAL_REFUND"),
                    ("SQUARE_REFUND", "SQUARE_REFUND"),
                ],
                max_length=20,
            ),
        ),
    ]
