# Generated by Django 3.2.10 on 2022-01-08 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payments", "0008_alter_payment_provider"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payment",
            new_name="Transaction",
        ),
    ]
