# Generated by Django 3.2.10 on 2022-01-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_rename_payment_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("PAYMENT", "Payment"), ("REFUND", "Refund")],
                default="PAYMENT",
                max_length=20,
            ),
        ),
    ]
