# Generated by Django 3.2.10 on 2022-01-08 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0010_alter_transaction_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="provider",
            new_name="provider_name",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="provider_payment_id",
            new_name="provider_transaction_id",
        ),
    ]
