# Generated by Django 3.2.12 on 2022-03-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_rename_purchase_type_on_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='provider_name',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('SQUARE_POS', 'SQUARE_POS'), ('SQUARE_ONLINE', 'SQUARE_ONLINE'), ('SQUARE_CONFECTIONERY', 'SQUARE_CONFECTIONERY'), ('MANUAL_CARD_REFUND', 'MANUAL_CARD_REFUND'), ('SQUARE_REFUND', 'SQUARE_REFUND')], max_length=20),
        ),
    ]
