# Generated by Django 3.2.14 on 2022-09-23 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0014_financialtransfer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FinancialTransfer",
        ),
    ]
