# Generated by Django 3.2.25 on 2025-03-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_delete_financialtransfer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-created_at"]},
        ),
    ]
