# Generated by Django 3.1.4 on 2020-12-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
