# Generated by Django 3.1.3 on 2020-11-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
