# Generated by Django 3.2.6 on 2021-08-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_auto_20210805_1525"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="addresses.address",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venue",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
