# Generated by Django 3.1.4 on 2020-12-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "__first__"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="addresses.address",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
