# Generated by Django 3.2.7 on 2021-09-23 10:01

import django_tiptap.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0002_auto_20210805_1525"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="description",
            field=django_tiptap.fields.TipTapTextField(blank=True, null=True),
        ),
    ]
