# Generated by Django 3.2.25 on 2025-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0005_venue_accessibility_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Contact email for the venue rather than production team",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
