# Generated by Django 3.2.25 on 2025-09-21 16:17

from django.db import migrations, models
import django_tiptap.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_auto_20250312_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='accessibility_short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='accessibility_info',
            field=django_tiptap.fields.TipTapTextField(blank=True, null=True),
        ),
    ]
