# Generated by Django 3.2.25 on 2024-06-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_results", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskresult",
            name="periodic_task_name",
            field=models.CharField(
                help_text="Name of the Periodic Task which was run",
                max_length=255,
                null=True,
                verbose_name="Periodic Task Name",
            ),
        ),
    ]
