# Generated by Django 4.2.25 on 2025-10-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_results", "0002_taskresult_periodic_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskresult",
            name="date_started",
            field=models.DateTimeField(
                default=None,
                help_text="Datetime field when the task was started in UTC",
                null=True,
                verbose_name="Started DateTime",
            ),
        ),
        migrations.AlterField(
            model_name="taskresult",
            name="status",
            field=models.CharField(
                default="PENDING",
                help_text="Current state of the task being run",
                max_length=50,
                verbose_name="Task State",
            ),
        ),
        migrations.AddIndex(
            model_name="taskresult",
            index=models.Index(
                fields=["periodic_task_name"], name="django_cele_periodi_1993cf_idx"
            ),
        ),
    ]
