on:
  schedule:
    # Run at 3am every day
    - cron:  '00 03 * * *'

env:
  BACKUPS_BUCKET: "uob-sta-backups"
  AWS_DEFAULT_REGION: "eu-west-2"

jobs:
  # https://github.com/schickling/dockerfiles/blob/master/postgres-backup-s3/backup.sh
  db-backup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ["uobtheatre-postgres-staging", "uobtheatre-postgres", "bristolsta-db"]
    steps:
      - name: Back up postgres service
        uses: appleboy/ssh-action@master
        env:
          SERVICE_NAME: ${{ matrix.service }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ $secrets.S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ envs.AWS_DEFAULT_REGION }}
          S3_BUCKET: ${{ envs.BACKUPS_BUCKET }}
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          envs: SERVICE_NAME,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_DEFAULT_REGION
          script: |
            cd /var/sta
            export BACKUP_NAME=dump_`echo $SERVICE_NAME`_`date +%d-%m-%Y"_"%H_%M_%S`.sql.gz
            docker-compose exec $SERVICE_NAME pg_dumpall -c -U postgres | gzip > dump.sql.gz
            cat dump.sql.gz | aws s3 cp - s3://$S3_BUCKET/$SERVICE_NAME/$BACKUP_NAME || exit 2
