name: Local (Dev) Build & Push

# Pushes a new image to the dev registry on every push to the dev branch (or manually triggered on a branch)
# The local/dev image is for frontend development: It is the one uobtheatre-web pulls when running locally

on:
  push:
    branches: [dev]

  workflow_dispatch:

env:
  IMAGE_NAME: api-dev
  IMAGE_OWNER: bristolsta

jobs:
  build-dev:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file compose/local/django/Dockerfile --tag ghcr.io/$IMAGE_OWNER/$IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.BRISTOLSTA_REGISTRY_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/$IMAGE_OWNER/$IMAGE_NAME:latest
