name: Docker build and push

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - [ dev ]

env:
  IMAGE_NAME: api-dev
  IMAGE_OWNER: bristolsta

jobs:
  build-dev:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file compose/local/django/Dockerfile --tag ghcr.io/$IMAGE_OWNER/$IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.BRISTOLSTA_REGISTRY_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/$IMAGE_OWNER/$IMAGE_NAME:latest
