name: Docker build and push

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

  workflow_dispatch:
    inputs:
      api-dev:
        description: 'Whether to build the api-dev container'
        required: false
        default: "false"
      api:
        description: 'Whether to build the api container'
        required: false
        default: "false"

env:
  IMAGE_NAME: api
  DEV_IMAGE_NAME: api-dev
  IMAGE_OWNER: bristolsta

jobs:
  build:
    if: ${{github.event.action}} != "workflow-dispatch" || ${{ github.event.inputs.api }} == "true"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file compose/production/django/Dockerfile --tag ghcr.io/$IMAGE_OWNER/$IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.BRISTOLSTA_REGISTRY_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/$IMAGE_OWNER/$IMAGE_NAME:latest

  build-dev:
    if: ${{github.event.action}} != "workflow-dispatch" || ${{ github.event.inputs.api-dev }} == "true"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file compose/local/django/Dockerfile --tag ghcr.io/$IMAGE_OWNER/$DEV_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.BRISTOLSTA_REGISTRY_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/$IMAGE_OWNER/$DEV_IMAGE_NAME:latest
