name: Package checks

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db_service:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: uobtheatre_api
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432


    steps:
    # Set up cache for pip packages
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Checkout the code
    - uses: actions/checkout@v2

    # Setup python
    - name: set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    # Install dependencies
    - name: Install dependencies
      run: pip install -r requirements/local.txt

    # Collect static
    - name: Collect Static
      run: ./manage.py collectstatic --noinput

    - name: Tests
      run: |
        pytest --cov uobtheatre --cov-fail-under 100 -m "not square_integration"
      env:
        DATABASE_URL: postgresql://postgres:postgres@0.0.0.0:5432/uobtheatre_api

    - name: System tests
      run: |
        pytest --cov uobtheatre -m "square_integration"
      env:
        DATABASE_URL: postgresql://postgres:postgres@0.0.0.0:5432/uobtheatre_api
        SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_SANDBOX_ACCESS_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
    # Set up cache for pip packages
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Checkout the code
    - uses: actions/checkout@v2

    # Setup python
    - name: set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    # Install dependencies
    - name: Install dependencies
      run: pip install -r requirements/local.txt

    - name: black - formatting
      run: |
        black uobtheatre

    - name: isort - sort imports
      run: |
        isort uobtheatre

    - name: pylint - linting
      run: |
        pylint uobtheatre

        # - name: mypy - static type checking
        #   run: |
        #     mypy uobtheatre

  schema:
    runs-on: ubuntu-latest
    steps:
    # Set up cache for pip packages
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Checkout the code
    - uses: actions/checkout@v2

    # Setup python
    - name: set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    # Install dependencies
    - name: Install dependencies
      run: pip install -r requirements/local.txt
    # Generate schmea
    - name: Generate schema
      run: |
        ./manage.py graphql_schema --schema uobtheatre.schema.schema --out schema.graphql

    # Push up the schema
    - name: Commit schema
      uses: EndBug/add-and-commit@v7.0.0
      with:
        message: 'Updated schema'
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
