name: Python package

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      db_service:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432


    steps:
    - uses: actions/checkout@v2

    - name: set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: pip install requirements.txt dev-requirements.txt

    - name: black - formatting
      run: |
        black uobtheatre

    - name: isort - sort imports
      run: |
        isort uobtheatre

    - name: pytest - check tests pass and coverage is 100%
      run: |
        pytest --cov uobtheatre --cov-fail-under 100
      env:
        DATABASE_URL: postgres://postgres:postgres@0.0.0.0:5432/postgres
