# Generated by Django 4.0.10 on 2025-10-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialtransfer",
            name="method",
            field=models.CharField(
                choices=[("INTERNAL", "Internal"), ("BACS", "BACS")],
                max_length=40,
            ),
        ),
    ]
